import {
  FormControl,
  MenuItem,
  Select,
  Card,
  CardContent,
} from "@material-ui/core";
import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";
import InfoBox from "./Components/InfoBox";
import Map from "./Components/Map";
import Table from "./Components/Table";
import LineGraph from "./Components/LineGraph";
import { sortData } from "./util";


export default function Home() {
  const [countries, setCountries] = useState([]);
  const [country, setCountry] = useState("worldwide");
  const [countryInfo, setCountryInfo] = useState({});
  const [tableData, setTableData] = useState([])



  useEffect(() => {
    
    fetch ("https://disease.sh/v3/covid-19/all")
    .then(response => response.json())
    .then(data => {
      setCountryInfo(data);
    })
  
    
  }, [])
  

  //STATE = How to write a variable in react

  // https://disease.sh/v3/covid-19/countries

  //USEEFFECT = Runs a piece of code
  // based on a given condition

  useEffect(() => {
    // async -> send a request, wait for it, do something with it.

    const getCountriesData = async () => {
      await fetch("https://disease.sh/v3/covid-19/countries")
        .then((response) => response.json())
        .then((data) => {
          const countries = data.map((country) => ({
            name: country.country,
            value: country.countryInfo.iso2,
          }));
          const sortedData = sortData(data);
          setTableData(sortedData);
          setCountries(countries);
        });
    };
    getCountriesData();
  }, []);

  const onCountryChange = async (event) => {
    const countryCode = event.target.value;

    setCountry(countryCode);

    const url =
      countryCode == "worldwide"
        ? "https://disease.sh/v3/covid-19/all"
        : `https://disease.sh/v3/covid-19/countries/${countryCode}`;

    await fetch(url)
      .then((response) => response.json())
      .then((data) => {
        // All of the data ....
        // from the country response
        setCountryInfo(data);
      });

      console.log("Country INFO>>>>", countryInfo);

    //https://disease.sh/v3/covid-19/all
    //https://disease.sh/v3/covid-19/countries/[COUNTRY_CODE]
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Covid-19 Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className={styles.main}></main> */}
      <div className={styles.app}>
        <div className={styles.app__left}>
          <div className={styles.app__header}>
            <h1>Covid Tracker</h1>
            <FormControl className="app__dropdown">
              <Select
                variant="outlined"
                value={country}
                onChange={onCountryChange}
              >
                {/* <MenuItem value="worldwide">Hello Wordwide</MenuItem>
              <MenuItem value="worldwide">Option 1</MenuItem>
              <MenuItem value="worldwide">Option 2</MenuItem>
              <MenuItem value="worldwide">Option 3</MenuItem> */}

                {/* Loop through all the countries list please */}
                <MenuItem value="worldwide">Worldwide</MenuItem>
                {countries.map((country) => (
                  <MenuItem value={country.value}>{country.name}</MenuItem>
                ))}
              </Select>
            </FormControl>
          </div>

          <div className={styles.app__stats}>
            <InfoBox title="Coronavirus Cases" cases={countryInfo.todayCases} total={countryInfo.cases} />

            <InfoBox title="Recovered" cases={countryInfo.todayRecovered} total={countryInfo.recovered} />

            <InfoBox title="Deaths" cases={countryInfo.todayDeaths} total={countryInfo.deaths} />
          </div>

          {/* Header */}
          {/* Title + Select input dropdown field */}

          {/* InfoBoxs */}
          {/* InfoBoxs */}
          {/* InfoBoxs */}

          {/* Table */}
          {/* Graph */}

          {/* Map */}

          <Map />
        </div>
        <Card className="app__right">
          <CardContent>
            <h3>Live Cases by Country</h3>
            <Table countries={tableData}/>
            <h3>Live Cases by Country</h3>
            <LineGraph />
            {/* Graph */}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
